name: vissal
favicon: null
layout_spectrum: 0.94951
typography_spectrum: 0.77011
title: Professional Photographer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-47711379-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e4f2fe'
    - '#9d8475'
    - '#000000'
    - '#cbbeb5'
    - '#262e36'
  brandStrength: 0.125
  lightness: 0.625
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
